# Generated by Django 5.1.2 on 2024-11-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0007_aluno_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alunos_count', models.IntegerField()),
                ('Alunos_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
