# Generated by Django 5.1.2 on 2024-11-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0008_alunoinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
