# Generated by Django 5.1.2 on 2024-11-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0009_aluno_bio_aluno_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='value',
        ),
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
